import gradio as gr
import requests
from Bio import Entrez, SeqIO
from io import StringIO
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
import os

Entrez.email = "public@example.com"
Entrez.tool = "PathogenAgent"

# بارگذاری مدل BioGPT شما
MODEL_NAME = "Sepideh2027/biogpt-clinvar-finetuned"

print("🔄 Loading model...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(MODEL_NAME)
model.eval()

if torch.cuda.is_available():
    model = model.to("cuda")
    print("✅ Model loaded on GPU")
else:
    print("✅ Model loaded on CPU")

# ========== ابزارها ==========

def search_pubmed(query):
    try:
        url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi"
        params = {"db": "pubmed", "term": query, "retmax": 3, "retmode": "json"}
        resp = requests.get(url, params=params, timeout=10)
        ids = resp.json().get("esearchresult", {}).get("idlist", [])
        if not ids:
            return "No articles found."
        url2 = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi"
        params2 = {"db": "pubmed", "id": ",".join(ids[:3]), "retmode": "json"}
        resp2 = requests.get(url2, params=params2, timeout=10)
        results = []
        for uid, rec in resp2.json().get("result", {}).items():
            if uid == "uids":
                continue
            results.append(f"- {rec.get('title', 'No title')}")
        return "📄 **PubMed Articles:**\n" + "\n".join(results)
    except Exception as e:
        return f"Error: {str(e)}"

def search_genbank(organism):
    try:
        handle = Entrez.esearch(db="nucleotide", term=f"{organism}[Organism] AND complete genome", retmax=1)
        record = Entrez.read(handle)
        handle.close()
        if not record["IdList"]:
            return f"No sequence found for '{organism}'."
        seq_id = record["IdList"][0]
        handle = Entrez.efetch(db="nucleotide", id=seq_id, rettype="fasta", retmode="text")
        seq_data = handle.read()
        handle.close()
        seq = SeqIO.read(StringIO(seq_data), "fasta")
        return f"🧬 **GenBank:**\n- {organism}\n- Length: {len(seq.seq):,} bp\n- {str(seq.seq[:200])}..."
    except Exception as e:
        return f"Error: {str(e)}"

def search_clinvar(variant):
    try:
        url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi"
        params = {"db": "clinvar", "term": variant, "retmax": 2, "retmode": "json"}
        resp = requests.get(url, params=params, timeout=10)
        ids = resp.json().get("esearchresult", {}).get("idlist", [])
        if not ids:
            return f"No ClinVar records for '{variant}'."
        url2 = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi"
        params2 = {"db": "clinvar", "id": ",".join(ids[:2]), "retmode": "json"}
        resp2 = requests.get(url2, params=params2, timeout=10)
        results = []
        for uid, rec in resp2.json().get("result", {}).items():
            if uid == "uids":
                continue
            sig = rec.get("clinicalsignificance", [{}])[0].get("description", "Unknown")
            results.append(f"- {rec.get('title', '')} → **{sig}**")
        return "🧬 **ClinVar:**\n" + "\n".join(results)
    except Exception as e:
        return f"Error: {str(e)}"

def pathogen_agent(query):
    query_lower = query.lower()
    if "pubmed" in query_lower or "article" in query_lower:
        return search_pubmed(query)
    elif "genbank" in query_lower or "genome" in query_lower:
        words = query.split()
        organism = " ".join(words[-2:]) if len(words) > 2 else query
        return search_genbank(organism)
    elif "clinvar" in query_lower or "variant" in query_lower:
        return search_clinvar(query)
    else:
        pubmed = search_pubmed(query)
        genbank = search_genbank(query)
        clinvar = search_clinvar(query)
        return f"""
## 🔍 Query: {query}

### 📄 PubMed
{pubmed}

### 🧬 GenBank
{genbank}

### 🧬 ClinVar
{clinvar}

---
**Generated by PathogenAgent v1.0**
"""

def process_query(query):
    if not query.strip():
        return "⚠️ Please enter a pathogen name, gene, or variant."
    return pathogen_agent(query)

# ========== رابط Gradio ==========

with gr.Blocks(title="PathogenAgent", theme=gr.themes.Soft()) as demo:
    gr.Markdown("""
    # 🧬 PathogenAgent: Agentic AI for Pathogen Genomic Analysis

    **Ask about any pathogen, gene, or variant.**  
    The agent will search PubMed, GenBank, and ClinVar.
    """)

    with gr.Row():
        query_input = gr.Textbox(
            label="🔬 Enter your query",
            placeholder="e.g., SARS-CoV-2 spike protein",
            lines=2
        )
        submit_btn = gr.Button("🚀 Analyze", variant="primary")

    output = gr.Markdown(label="📊 Report")

    submit_btn.click(fn=process_query, inputs=query_input, outputs=output)

    gr.Markdown("""
    ### 📌 Examples
    - `SARS-CoV-2 genome`
    - `BRCA1 c.68_69delAG`
    - `Ebola virus`
    """)

demo.launch()
